/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
    './styles/**/*.css', // ✅ correct glob
    './pages/**/*.{ts,tsx,js,jsx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      container: { center: true, padding: '1rem' },
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'system-ui',
          'Segoe UI',
          'Tahoma',
          'Geneva',
          'Verdana',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SF Mono',
          'Monaco',
          'Cascadia Code',
          'Roboto Mono',
          'Courier New',
          'monospace',
        ],
      },
      colors: {
        primary: {
          50: 'var(--pnx-primary-50)',
          100: 'var(--pnx-primary-100)',
          200: 'var(--pnx-primary-200)',
          300: 'var(--pnx-primary-300)',
          400: 'var(--pnx-primary-400)',
          500: 'var(--pnx-primary-500)',
          600: 'var(--pnx-primary-600)',
          700: 'var(--pnx-primary-700)',
          800: 'var(--pnx-primary-800)',
          900: 'var(--pnx-primary-900)',
          DEFAULT: 'var(--pnx-primary)',
        },
        secondary: {
          50: 'var(--pnx-secondary-50)',
          100: 'var(--pnx-secondary-100)',
          200: 'var(--pnx-secondary-200)',
          300: 'var(--pnx-secondary-300)',
          400: 'var(--pnx-secondary-400)',
          500: 'var(--pnx-secondary-500)',
          600: 'var(--pnx-secondary-600)',
          700: 'var(--pnx-secondary-700)',
          800: 'var(--pnx-secondary-800)',
          900: 'var(--pnx-secondary-900)',
          DEFAULT: 'var(--pnx-secondary)',
        },
        success: {
          50: 'var(--pnx-success-50)',
          100: 'var(--pnx-success-100)',
          500: 'var(--pnx-success-500)',
          600: 'var(--pnx-success-600)',
          700: 'var(--pnx-success-700)',
          DEFAULT: 'var(--pnx-success)',
        },
        warning: {
          50: 'var(--pnx-warning-50)',
          100: 'var(--pnx-warning-100)',
          500: 'var(--pnx-warning-500)',
          600: 'var(--pnx-warning-600)',
          700: 'var(--pnx-warning-700)',
          DEFAULT: 'var(--pnx-warning)',
        },
        error: {
          50: 'var(--pnx-error-50)',
          100: 'var(--pnx-error-100)',
          500: 'var(--pnx-error-500)',
          600: 'var(--pnx-error-600)',
          700: 'var(--pnx-error-700)',
          DEFAULT: 'var(--pnx-error)',
        },
        info: {
          50: 'var(--pnx-info-50)',
          100: 'var(--pnx-info-100)',
          500: 'var(--pnx-info-500)',
          600: 'var(--pnx-info-600)',
          700: 'var(--pnx-info-700)',
          DEFAULT: 'var(--pnx-info)',
        },
      },
      spacing: {
        0: 'var(--pnx-space-0)',
        1: 'var(--pnx-space-1)',
        2: 'var(--pnx-space-2)',
        3: 'var(--pnx-space-3)',
        4: 'var(--pnx-space-4)',
        5: 'var(--pnx-space-5)',
        6: 'var(--pnx-space-6)',
        8: 'var(--pnx-space-8)',
        10: 'var(--pnx-space-10)',
        12: 'var(--pnx-space-12)',
        16: 'var(--pnx-space-16)',
        20: 'var(--pnx-space-20)',
        24: 'var(--pnx-space-24)',
        32: 'var(--pnx-space-32)',
      },
      borderRadius: {
        none: 'var(--pnx-radius-none)',
        sm: 'var(--pnx-radius-sm)',
        DEFAULT: 'var(--pnx-radius)',
        md: 'var(--pnx-radius-md)',
        lg: 'var(--pnx-radius-lg)',
        xl: 'var(--pnx-radius-xl)',
        '2xl': 'var(--pnx-radius-2xl)',
        full: 'var(--pnx-radius-full)',
      },
      boxShadow: {
        none: 'var(--pnx-shadow-none)',
        xs: 'var(--pnx-shadow-xs)',
        sm: 'var(--pnx-shadow-sm)',
        DEFAULT: 'var(--pnx-shadow)',
        md: 'var(--pnx-shadow-md)',
        lg: 'var(--pnx-shadow-lg)',
        xl: 'var(--pnx-shadow-xl)',
        '2xl': 'var(--pnx-shadow-2xl)',
        subtle: 'var(--pnx-shadow-subtle)',
        inner: 'var(--pnx-shadow-inner)',
      },
      fontSize: {
        xs: ['var(--pnx-text-xs)', { lineHeight: 'var(--pnx-leading-normal)' }],
        sm: ['var(--pnx-text-sm)', { lineHeight: 'var(--pnx-leading-normal)' }],
        base: ['var(--pnx-text-base)', { lineHeight: 'var(--pnx-leading-normal)' }],
        lg: ['var(--pnx-text-lg)', { lineHeight: 'var(--pnx-leading-normal)' }],
        xl: ['var(--pnx-text-xl)', { lineHeight: 'var(--pnx-leading-snug)' }],
        '2xl': ['var(--pnx-text-2xl)', { lineHeight: 'var(--pnx-leading-snug)' }],
        '3xl': ['var(--pnx-text-3xl)', { lineHeight: 'var(--pnx-leading-snug)' }],
        '4xl': ['var(--pnx-text-4xl)', { lineHeight: 'var(--pnx-leading-tight)' }],
        '5xl': ['var(--pnx-text-5xl)', { lineHeight: 'var(--pnx-leading-tight)' }],
        '6xl': ['var(--pnx-text-6xl)', { lineHeight: 'var(--pnx-leading-tight)' }],
        '7xl': ['var(--pnx-text-7xl)', { lineHeight: 'var(--pnx-leading-tight)' }],
      },
      zIndex: {
        base: 'var(--pnx-z-base)',
        dropdown: 'var(--pnx-z-dropdown)',
        sticky: 'var(--pnx-z-sticky)',
        fixed: 'var(--pnx-z-fixed)',
        'modal-backdrop': 'var(--pnx-z-modal-backdrop)',
        modal: 'var(--pnx-z-modal)',
        popover: 'var(--pnx-z-popover)',
        tooltip: 'var(--pnx-z-tooltip)',
        toast: 'var(--pnx-z-toast)',
        max: 'var(--pnx-z-max)',
      },
      transitionDuration: {
        fast: 'var(--pnx-transition-fast)',
        base: 'var(--pnx-transition-base)',
        slow: 'var(--pnx-transition-slow)',
        slower: 'var(--pnx-transition-slower)',
      },
      transitionTimingFunction: {
        'ease-in': 'var(--pnx-ease-in)',
        'ease-out': 'var(--pnx-ease-out)',
        'ease-in-out': 'var(--pnx-ease-in-out)',
      },
    },
  },
  plugins: [],
};
